export const weatherCodes = {
    0: {"description": "Clear sky", "icon": 'ri-sun-line', 'picture': 'clear'},
    1: {"description": "Mainly clear", "icon": 'ri-sun-foggy-line', 'picture': 'mainly_clear'},
    2: {"description": "Partly cloudy", "icon": 'ri-sun-cloudy-line', 'picture': 'cloud'},
    3: {"description": "Overcast", "icon": 'ri-cloud-line', 'picture': 'cloud'},
    45: {"description": "Fog", "icon": 'ri-mist-line', 'picture': 'fog'},
    48: {"description": "Depositing rime fog", "icon": 'ri-snowy-line', 'picture': 'fog'},
    51: {"description": "Light drizzle", "icon": 'ri-drizzle-line', 'picture': 'rain'},
    56: {"description": "Light freezing drizzle", "icon": 'ri-drizzle-line', 'picture': 'rain'},
    61: {"description": "Slight rain", "icon": 'ri-drizzle-line', 'picture': 'rain'},
    66: {"description": "Light freezing rain", "icon": 'ri-drizzle-line', 'picture': 'rain'},
    53: {"description": "Moderate drizzle", "icon": 'ri-showers-line', 'picture': 'rain'},
    55: {"description": "Dense drizzle", "icon": 'ri-showers-line', 'picture': 'rain'},
    57: {"description": "Dense freezing drizzle", "icon": 'ri-showers-line', 'picture': 'rain'},
    67: {"description": "Heavy freezing rain", "icon": 'ri-showers-line', 'picture': 'rain'},
    80: {"description": "Slight rain showers", "icon": 'ri-showers-line', 'picture': 'rain'},
    63: {"description": "Moderate rain", "icon": 'ri-rainy-line', 'picture': 'rain'},
    81: {"description": "Moderate rain showers", "icon": 'ri-rainy-line', 'picture': 'rain'},
    65: {"description": "Heavy rain", "icon": 'ri-heavy-showers-line', 'picture': 'rain'},
    82: {"description": "Violent rain showers", "icon": 'ri-heavy-showers-line', 'picture': 'rain'},
    71: {"description": "Slight snow fall", "icon": 'ri-snowy-line', 'picture': 'snow'},
    73: {"description": "Moderate snow fall", "icon": 'ri-snowy-line', 'picture': 'snow'},
    75: {"description": "Heavy snow fall", "icon": 'ri-snowflake-line', 'picture': 'snow'},
    77: {"description": "Snow grains", "icon": 'ri-snowflake-line', 'picture': 'snow'},
    85: {"description": "Slight snow showers", "icon": 'ri-snowflake-line', 'picture': 'snow'},
    86: {"description": "Heavy snow showers", "icon": 'ri-snowflake-line', 'picture': 'snow'},
    95: {"description": "Thunderstorm (slight or moderate)", "icon": 'ri-thunderstorms-line', 'picture': 'thunder'},
    96: {"description": "Thunderstorm with slight hail", "icon": 'ri-hail-line', 'picture': 'thunder'},
    99: {"description": "Thunderstorm with heavy hail", "icon": 'ri-hail-line', 'picture': 'thunder'}
};