export const weatherCodes = {
    0: {"description": "Clear sky", "icon": 'ri-sun-line'},
    1: {"description": "Mainly clear", "icon": 'ri-sun-foggy-line'},
    2: {"description": "Partly cloudy", "icon": 'ri-sun-cloudy-line'},
    3: {"description": "Overcast", "icon": 'ri-cloud-line'},
    45: {"description": "Fog", "icon": 'ri-mist-line'},
    48: {"description": "Depositing rime fog", "icon": 'ri-snowy-line'},
    51: {"description": "Light drizzle", "icon": 'ri-drizzle-line'},
    56: {"description": "Light freezing drizzle", "icon": 'ri-drizzle-line'},
    61: {"description": "Slight rain", "icon": 'ri-drizzle-line'},
    66: {"description": "Light freezing rain", "icon": 'ri-drizzle-line'},
    53: {"description": "Moderate drizzle", "icon": 'ri-showers-line'},
    55: {"description": "Dense drizzle", "icon": 'ri-showers-line'},
    57: {"description": "Dense freezing drizzle", "icon": 'ri-showers-line'},
    67: {"description": "Heavy freezing rain", "icon": 'ri-showers-line'},
    80: {"description": "Slight rain showers", "icon": 'ri-showers-line'},
    63: {"description": "Moderate rain", "icon": 'ri-rainy-line'},
    81: {"description": "Moderate rain showers", "icon": 'ri-rainy-line'},
    65: {"description": "Heavy rain", "icon": 'ri-heavy-showers-line'},
    82: {"description": "Violent rain showers", "icon": 'ri-heavy-showers-line'},
    71: {"description": "Slight snow fall", "icon": 'ri-snowy-line'},
    73: {"description": "Moderate snow fall", "icon": 'ri-snowy-line'},
    75: {"description": "Heavy snow fall", "icon": 'ri-snowflake-line'},
    77: {"description": "Snow grains", "icon": 'ri-snowflake-line'},
    85: {"description": "Slight snow showers", "icon": 'ri-snowflake-line'},
    86: {"description": "Heavy snow showers", "icon": 'ri-snowflake-line'},
    95: {"description": "Thunderstorm (slight or moderate)", "icon": 'ri-thunderstorms-line'},
    96: {"description": "Thunderstorm with slight hail", "icon": 'ri-hail-line'},
    99: {"description": "Thunderstorm with heavy hail", "icon": 'ri-hail-line'}
};
